//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datawarehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int PK { get; set; }
        public Nullable<int> seller_FK { get; set; }
        public Nullable<int> product_FK { get; set; }
        public Nullable<int> city_FK { get; set; }
        public Nullable<int> pos_FK { get; set; }
        public System.DateTime date { get; set; }
        public int amount { get; set; }
        public decimal price { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual PointOfSales PointOfSales { get; set; }
        public virtual Products Products { get; set; }
        public virtual Sellers Sellers { get; set; }
    }
}
